import { Home } from './Home'
// import { MenuPage } from './MenuPage'
import { Contact } from './Contact'
import { Landing } from './Landing'
import { LandingLoading } from './LandingLoading'
import { LocationPage } from './LocationPage'
import { OrderPage } from './OrderPage'
import { GoFoodPage } from './OutletPage/GoFood'
import { GrabFood } from './OutletPage/GrabFood'
import { ShopeeFood } from './OutletPage/ShopeeFood'
import { Login } from './Login'
import { NotFound } from './NotFound'
import { SecondPage } from './SecondPage'

export { Home, Contact, Landing, LandingLoading, LocationPage, OrderPage, GoFoodPage, GrabFood, ShopeeFood, Login, NotFound, SecondPage }
